spring.application.name=springboot-restful-webservices

spring.datasource.url=jdbc:mysql://localhost:3306/user_management
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

management.endpoints.web.exposure.include=*


#actuator/info
management.info.env.enabled=true

info.app.name=Spring Boot Restful Web Services
info.app.description=Spring Boot Restful Web Services Demo
info.app.version=1.0.0

#actuator/health
management.endpoint.health.show-details=always

